### ISSUE TITLE
can't install with capacitor 4.0.x core

### ISSUE THREAD

**Issue by ASHBAW** [capacitor-community/keep-awake#33] opened 2022-08-03 17:46 UTC
Doesn't look like this works with capacitor core 4.0.x yet?

```
npm ERR! While resolving: ionic6_summit2_capacitor_14@0.0.1
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor-community/keep-awake@2.1.1
npm ERR! node_modules/@capacitor-community/keep-awake
npm ERR!   @capacitor-community/keep-awake@"*" from the root project
```

**Comment by pwespi** [comment] 2022-08-03 18:43
See https://github.com/capacitor-community/keep-awake/pull/32

**Comment by robingenz** [comment] 2022-08-03 20:29
Duplicate of #31

**Closed by robingenz** 2022-08-03 20:29 UTC
